export const MOST_SOLD_BOOKS = "MOST_SOLD_BOOKS";
export const MOST_SOLD_PHONES = "MOST_SOLD_PHONES";
export const GET_PAGINATED_BOOKS = "GET_PAGINATED_BOOKS";
export const GET_PAGINATED_PHONES = "GET_PAGINATED_PHONES";
export const GET_RELATED_PRODUCTS = "GET_RELATED_PRODUCTS";
export const GET_SINGLE_PRODUCT = "GET_SINGLE_PRODUCT";



